spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
